### PR TITLE
Fix text node

### PR DESCRIPTION
**Pull request by SpyR1014**
@monalena @ghazal-karami 

I've added a new data element to the vue component called `closeObservable`.

It allows observables to be cancelled. In doing so I've cleaned up the Text nodes so they are exclusive and don't bug out as easily.

Fixed:
 - Clicking a node multiple times will not create multiple pipes.
 - Changing the state of the mouse will always turn off text editing (preventing you from getting trapped in edit mode)
 - When a saved graph is pushed, the new

### CODE REVIEW

**Comment by SpyR1014** [comment]
My change doesn't appear to reflect the newest code. I'll review before merging.

**Comment by ghazal-karami** [comment]
So I am going to push first. OK?

**Comment by SpyR1014** [comment]
Yep push first :)

**Comment by ghazal-karami** [comment]
Pushed.

**Pull request closed without merging**
